	<div style="margin-left:20%;font-size:15px;">附件1</div></br>
	<center><div style="font-size:35px;font-weight:bold;">骨干企业困难和问题信息采集表</div></center></br></br></br></br>
	<table width="70%" align=center><tr><td width="20%">组别：$entGroup.name$</td>  <td width="50%">县区：$entCounty.name$</td><td>提报时间:$entproblem.problemReportdate$</td></tr></table>
	<table style="font-size:18px;" width="70%" align=center border="0" class="contentprint" cellpadding="0" cellspacing="0">
		<tr>
			<td >企业名称</td>
			<td colspan="5" width="190" valign="middle">$entinfos.entName$</td>
		</tr>
		<tr>
			<td width="18%">企业联系人</td>
			<td>$entproblem.entinfos.entMessenger$</td>
			<td >职务</td>
			<td>$entproblem.entinfos.entDuty2$</td>
			<td >联系电话</td>
			<td>$entproblem.entinfos.entTel2$</td>
		</tr>
		
		<tr>
			<td >存在的困难和问题描述</td>
			<td colspan="5" valign="middle">$entproblem.problem$</td>
		</tr>
		
		<tr>
			<td >问题解决已具备条件和完成情况</td>
			<td colspan="5"  valign="middle">$entproblem.buildCondition$</td>
		</tr>
		<tr>
			<td >问题解决涉及的单位（含县区、部门）</td>
			<td colspan="5" valign="middle">$entproblem.dealUnit$</td>
		</tr>
		<tr>
			<td >解决问题是否已与相关单位进行过联系，相关单位有何意见及理由</td>
			<td colspan="5" valign="middle">$entproblem.dealOpinion$</td>
		</tr>
		<tr>
			<td >企业期望问题何时得到解决</td>
			<td colspan="5">$entproblem.expectDate$</td>
			</tr>
	</table>
	